title: Emory CIDMATH
description: Emory CIDMATH Github Page
theme: just-the-docs

url: https://emory-cidmath.github.io/emory-cidmath

aux_links:
  Site Repository: https://github.com/Emory-CIDMATH/emory-cidmath.github.io/
