project:
  type: website
  output-dir: docs

website:
  title: "Emory CIDMATH"
  site-url: https://cidmath.github.io
  repo-url: https://github.com/cidmath/cidmath.github.io
  google-analytics: "G-LP1624XJQE"
  cookie-consent: true
  open-graph: true
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - href: data-platform.html
        text: "CIDMATH Data Platform"
      - href: wastewater-epi.html
        text: "Wastewater Epidemiology"
      - href: social-contact.html
        text: "Social Contact Patterns"
      - href: vaccine-epi.html
        text: "Vaccine Epidemiology"
      - href: forecasting.html
        text: "Disease Forecasting"

execute:
  freeze: auto

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



